armor/urls.py
from django.conf.urls import url
from . import views

app_name = 'armor'

urlpatterns = [
    url(r'^$', views.armorview, name='armorview'),
    url(r'^(?P<armor_id>[0-9]+)/$', views.detail, name='detail')
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cartview, name='cartview')
]

helmets/urls.py
from django.conf.urls import url
from . import views

app_name = 'helmet'

urlpatterns = [
    url(r'^$', views.helmetview, name='helmetview'),
    url(r'^(?P<helmet_id>[0-9]+)/$', views.detail, name='detail')
]

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.homeview, name='homeview')
]

store/urls.py
from django.conf.urls import url
from . import views

app_name = 'store'

urlpatterns = [
    #/store/
    url(r'^$', views.index, name='index'),

    #/store/product_id
    url(r'^(?P<product_id>[0-9]+)/$', views.detail, name='detail'),

    # /store/product_id/purchase/
    url(r'^(?P<product_id>[0-9]+)/purchase/$', views.purchase, name='purchase'),

    # /store/product_id/purchase/cart/
    url(r'^(?P<product_id>[0-9]+)/purchase/cart$', views.cart, name='cart')
]

swords/urls.py
from django.conf.urls import url
from . import views

app_name = 'sword'

urlpatterns = [
    url(r'^$', views.swordview, name='swordview'),
    url(r'^(?P<sword_id>[0-9]+)/$', views.detail, name='detail')
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^helmets/', include('helmets.urls')),
    url(r'^swords/', include('swords.urls')),
    url(r'^armor/', include('armor.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^cart/', include('cart.urls'))
]

viking/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^store/', include('store.urls')),
]

armor/models.py
from django.db import models


class ArmorM(models.Model):
    type = models.CharField(max_length=50)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=1000)
    item_number = models.IntegerField()
    price = models.FloatField()
    picture = models.CharField(max_length=1000)

    def __str__(self):
        return self.type + ' - ' + self.name + ' - ' + str(self.price)

cart/models.py
from django.db import models

helmets/models.py
from django.db import models


class HelmetsM(models.Model):
    type = models.CharField(max_length=50)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=1000)
    item_number = models.IntegerField()
    price = models.FloatField()
    picture = models.CharField(max_length=1000)

    def __str__(self):
        return self.type + ' - ' + self.name + ' - ' + str(self.price)

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

store/models.py
from django.db import models

class Products(models.Model):
    product_id = models.IntegerField
    type = models.CharField(max_length=25)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    quantity = models.IntegerField()
    price = models.FloatField()
    picture = models.CharField(max_length=500)
    is_purchased = models.BooleanField(default=False)

    def __str__(self):                                      #what does this do?
        return self.type + ' - ' + self.name

class Cart(models.Model):
    product = models.ForeignKey(Products)
    name = models.CharField(max_length=100)
    quantity = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()

class Customer(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=150)

swords/models.py
from django.db import models


class SwordsM(models.Model):
    type = models.CharField(max_length=50)
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=1000)
    item_number = models.IntegerField()
    price = models.FloatField()
    picture = models.CharField(max_length=1000)

    def __str__(self):
        return self.type + ' - ' + self.name + ' - ' + str(self.price)

armor/views.py
from django.shortcuts import render, get_object_or_404
from . models import ArmorM


def armorview(request):
    all_armors = ArmorM.objects.all()
    return render(request, 'armor/index.html', {'all_armors': all_armors})


def detail(request, armor_id):
    armor = get_object_or_404(ArmorM, pk=armor_id)
    return render(request, 'armor/detail.html', {'armor': armor})

cart/views.py
from django.http import HttpResponse
from django.template import loader


def cartview(request):
    template = loader.get_template('cart/index.html')
    return HttpResponse(template.render(request))

helmets/views.py
from django.shortcuts import render, get_object_or_404
from . models import HelmetsM


def helmetview(request):
    all_helmets = HelmetsM.objects.all()
    return render(request, 'helmets/index.html', {'all_helmets': all_helmets})


def detail(request, helmet_id):
    helmet = get_object_or_404(HelmetsM, pk=helmet_id)
    return render(request, 'helmets/detail.html', {'helmet': helmet})

home/views.py
from django.shortcuts import render


def homeview(request):
    return render(request, 'home/index.html', {})

store/views.py
from django.shortcuts import render, get_object_or_404
from . models import Products


def index(request):
    all_products = Products.objects.all()
    return render(request, 'store/index.html', {'all_products': all_products})


def detail(request, product_id):
    product = get_object_or_404(Products, pk=product_id)
    return render(request, 'store/detail.html', {'product': product})


def purchase(request, product_id):
    product = get_object_or_404(Products, pk=product_id)
    return render(request, 'store/purchase.html', {'product': product})

def cart(request, product_id):   #attach to purchase
    product = get_object_or_404(Products, pk=product_id)

swords/views.py
from django.shortcuts import render, get_object_or_404
from . models import SwordsM


def swordview(request):
    all_swords = SwordsM.objects.all()
    return render(request, 'swords/index.html', {'all_swords': all_swords})


def detail(request, sword_id):
    sword = get_object_or_404(SwordsM, pk=sword_id)
    return render(request, 'swords/detail.html', {'sword': sword})

armor/templates/armor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}The Viking Store{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'armor/style.css' %}" />
    <script scr="https://ajax.googleapix.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script scr="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <li class = "active">
                <a href="../home/" class="navbar-brand">The Viking Store</a><!--missing href url-->
            </li>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class = "">
                    <a href="">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Armor<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../helmets/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Helmets<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../swords/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Swords<!--missing href url-->
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right"><!--missing href url-->
                <li class="">
                    <a href="../cart/">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Cart
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

armor/templates/armor/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}The Viking Store{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'armor/style.css' %}" />
    <script scr="https://ajax.googleapix.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script scr="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <li class = "active">
                <a href="../../home/" class="navbar-brand">The Viking Store</a><!--missing href url-->
            </li>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class = "">
                    <a href="../../armor/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Armor<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../../helmets/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Helmets<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../../swords/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Swords<!--missing href url-->
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right"><!--missing href url-->
                <li class="">
                    <a href="../../cart/">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Cart
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

 <div class="floated_img">
                    <img style="float: left; margin: 0px 0px 15px 15px;" src="{{ armor.picture }}"
                    class="img-rounded" width="600" height="750" />
 </div>

<h1>{{ armor.type }}</h1>
<h3>{{ armor.name }}</h3>
<h3>{{ armor.description }}</h3>
<h3>${{ armor.price }}</h3>
<button class="btn btn-default"><a href="../../cart/">Add to Cart</a></button>

</body>
</html>


armor/templates/armor/index.html
{% extends 'armor/base.html' %}
{% block title %}Armor{% endblock %}

{% block body %}

{% if all_armors %}
    {% for armor in all_armors %}
            <div class="floated_img">
                <a href="/armor/{{ armor.id }}/">
            <img style="float: left; margin: 0px 0px 15px 15px;" src="{{ armor.picture }}"
                    class="img-rounded" width="300" height="300" />
                    </a>
           </div>
    {% endfor %}
{% else %}
    <h3>No armor is available.</h3>
{% endif %}

{% endblock %}



cart/templates/cart/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Shopping Cart</title>
 <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <!--<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>-->
    <!--<link rel="stylesheet" type="text/css" href="{% static 'armor/style.css' %}" /> -->
    <!--<script scr="https://ajax.googleapix.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>-->
    <!--<script scr="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>-->

  </head>

  <body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <li class = "active">
                    <a href="../../home/" class="navbar-brand">The Viking Store</a><!--missing href url-->
                </li>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class = "">
                        <a href="../../armor/">
                            <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Armor<!--missing href url-->
                        </a>
                    </li>
                    <li class = "">
                        <a href="../../helmets/">
                            <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Helmets<!--missing href url-->
                        </a>
                    </li>
                    <li class = "">
                        <a href="../../swords/">
                            <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Swords<!--missing href url-->
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right"><!--missing href url-->
                    <li class="">
                        <a href="../../cart/">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Cart
                        </a>
                    </li>
                </ul>
            </div>
            </div>
        </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-xs-12">
                <div class="panel panel-info">
                      <div class="panel-heading">
                        <div class="panel-title">
                            <div class="row">
                                <div class="col-md-6">
                                    <h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
                                </div>
                                <div class="col-md-6">
                                    <button class="btn btn-default btn-sm pull-right"><a href="../home">Continue Shopping</a></button>
                                </div>
                            </div>
                        </div>
                      </div>
                </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-mid-2 col-xs-12">
                         <div class="floated_img">
                            <img style="float: left; margin: 0px 0px 15px 15px;" src="{{ armor.picture }}"
                            class="img-rounded" width="150" height="70" />
                         </div>
                    </div>
                </div>
            </div>
                <div class="panel-footer">total</div>
            </div>
        </div>
    </div>
  </body>
</html>

helmets/templates/helmets/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}The Viking Store{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'armor/style.css' %}" />
    <script scr="https://ajax.googleapix.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script scr="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <li class = "active">
                <a href="../home/" class="navbar-brand">The Viking Store</a><!--missing href url-->
            </li>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class = "">
                    <a href="../armor/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Armor<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Helmets<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../swords/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Swords<!--missing href url-->
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right"><!--missing href url-->
                <li class="">
                    <a href="../cart/">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Cart
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

helmets/templates/helmets/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}The Viking Store{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'armor/style.css' %}" />
    <script scr="https://ajax.googleapix.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script scr="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <li class = "active">
                <a href="../../home/" class="navbar-brand">The Viking Store</a><!--missing href url-->
            </li>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class = "">
                    <a href="../../armor/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Armor<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../../helmets/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Helmets<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../../swords/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Swords<!--missing href url-->
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right"><!--missing href url-->
                <li class="">
                    <a href="../../cart/">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Cart
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

 <div class="floated_img">
                    <img style="float: left; margin: 0px 0px 15px 15px;" src="{{ helmet.picture }}"
                    class="img-rounded" width="600" height="750" />
 </div>

<h1>{{ helmet.type }}</h1>
<h3>{{ helmet.name }}</h3>
<h3>{{ helmet.description }}</h3>
<h3>${{ helmet.price }}</h3>

</body>
</html>



helmets/templates/helmets/index.html
{% extends 'helmets/base.html' %}
{% block title %}Helmets{% endblock %}

{% block body %}

    {% if all_helmets %}
       {% for helmet in all_helmets %}
            <div class="floated_img">
                <a href="/helmets/{{ helmet.id }}/">
            <img style="float: left; margin: 0px 0px 15px 15px;" src="{{ helmet.picture }}"
                    class="img-rounded" width="300" height="300" />
                    </a>
           </div>
        {% endfor %}
    {% else %}
        <h3>No helmets are available.</h3>
    {% endif %}


{% endblock %}

home/templates/home/base.html
  <!-- Loads the path to your static files -->
      {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Rakkas' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}The Viking Store{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <li class = "">
                <a href="" class="navbar-brand">The Viking Store</a><!--missing href url-->
            </li>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class = "">
                    <a href="../armor/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Armor<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../helmets/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Helmets<!--missing href url-->
                    </a>
                </li>
                 <li class = "">
                    <a href="../swords/">
                        <span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Swords<!--missing href url-->
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right"><!--missing href url-->
                <li class="">
                    <a href="../cart/">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp; Cart
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block title %}Home{% endblock %}

{% block body %}

    <h1 class="text-center" style="font-family:rakkas"><font color="#254117"><p style="font-size:65px">The Viking Store</p></font></h1>

         <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
            <a href="../helmets/">
          <img src="../../static/home/images/vikinghelmet.jpg" alt="Helmet" style="width:1500px;height:600px">
                </a>
          <div class="carousel-caption">
            <h3>Helmet</h3>
            <p>The helmet of iron clad grit.</p>
          </div>
        </div>

        <div class="item">
            <a href="../swords/">
          <img src="../../static/home/images/swords.jpeg" alt="Sword" style="width:1500px;height:600px">
            </a>
          <div class="carousel-caption">

            <h3>Swords</h3>
            <p>The sharpest piercing piercers ever.</p>
          </div>
        </div>

        <div class="item">
            <a href="../armor/">
          <img src="../../static/home/images/armor.jpg" alt="Armor" style="width:1500px;height:600px">
            </a>
          <div class="carousel-caption">
            <h3>Armor</h3>
            <p>No blood out and no entry into this gut.</p>
          </div>
        </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>

    </div>


{% endblock %}

store/templates/store/detail.html
<body style="background-color:skyblue">
<img src="{{ product.picture }}">

<h2>Type: {{ product.type }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<h2>Name: {{ product.name }}</h2>
<h2>Description: {{ product.description }}</h2><br>

<form action="{% url 'store:purchase' product.id%}" method="post">
    {% csrf_token %}
    <input type="submit" value="Add to Cart">
</form>

store/templates/store/index.html
<body style="background-color:yellow">
{% if all_products %}
    <h1>Viking Gear:</h1><br>
    <h2>Helmets</h2>
    <ul>
        {% for product in all_products %}
        <li><a href="{% url 'store:detail' product.id %}">{{ product.name }}</a></li>
        {% endfor %}
    </ul>
    <h2>Armor</h2>
    <ul>
        {% for product in all_products %}
        <li><a href="{% url 'store:detail' product.id %}">{{ product.name }}</a></li>
        {% endfor %}
    </ul>
    <h2>Footwear</h2>
    <ul>
        {% for product in all_products %}
        <li><a href="{% url 'store:detail' product.id %}">{{ product.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>Product not found or product no longer available.</h3>
{% endif %}

store/templates/store/purchase.html
<body style="background-color:gray">

<h2>This is the Cart</h2>

<ul>

    <h3>Item: {{ product.name }} </h3>
    <h3>Item price: {{ product.price }} </h3>
    <h3>Quantity In-Stock: {{ product.quantity }} </h3>

</ul>